### ISSUE TITLE
I can't seem to get table population working

### ISSUE THREAD

**Issue by shiang-luong** [Samir-Sell/templatepptx#1]
Just to add, regular substitution works.  It's just the table one I'm having issues with.

I have this in my context:
`     "relationship_test" : [ # This key contains the list which can contain an unlimited amount of records to populate a table.
        {
            "id" : "1",
            "first_name" : "Duncan",
            "last_name" : "Junior"
        },
        {
            "id" : "2",
            "first_name" : "Jessica",
            "last_name" : "Jones"
        }
    ]`

and my variables are specified in the template:
![image](https://user-images.githubusercontent.com/48106860/235523707-7d87cfba-a0c0-4ab7-820d-980e25c24a06.png)

I am getting this error:
> python/site-packages/table_factory.py:87: UserWarning: Table failed to be populated due to list index out of range
  warnings.warn(f"Table failed to be populated due to {e}")

I maybe confused with the documentation here:
`Additionally, tables can be populated with an unlmited number of related data by specifying a list of dictionaries in your context. A related table variable is specified in the template by adding the prefix "relationship_" to the front of the key. Please observe the following example of a context object below.`

if you can help.  Also if you can include your pptx files you used for test.py would be helpful too

**Comment by shiang-luong** [comment]
Also thanks for sharing this library.  It will hopefully be useful for me.

**Comment by Samir-Sell** [comment]
Sorry it took longer than I thought to get back to you.

I have updated the test.py to hopefully be more clear. I tested this using Python 3.9.16 as I was having problems with pptx library on 3.11.

I have used your context and uploaded the powerpoints I used in the test.py with relative paths now.

You must specify the correct relationship name. Your example context was "test". The "relationship_" part is only to inform the script that you are referring to a relationship. I added another example in test.py for a relationship called "people". 

You must also specify in the second row of the table which key it should pull from for the relationship dictionary. Sorry the documentation is not better! I will hopefully make it better and add more features in the future.

I pushed the changes to test.py and uploaded my input and output pptx for you to look at.

Examples below based on this context:

```python
context = {
    "random_key" : "random_value",
         "relationship_test" : [ 
             { "id" : "1", "first_name" : "Duncan", "last_name" : "Junior" }, 
             { "id" : "2", "first_name" : "Jessica", "last_name" : "Jones" } 
          ],
          # Same relationship as a above but with the name "people" instead of "test"
         "relationship_people" : [ 
             { "id" : "3", "first_name" : "Duncan", "last_name" : "Junior" }, 
             { "id" : "4", "first_name" : "Jessica", "last_name" : "Jones" } 
          ]
    }
```

![inputexample](https://user-images.githubusercontent.com/67107744/236688025-e1d40fad-1719-41cd-8288-e920828a78cb.PNG)
![outputexample](https://user-images.githubusercontent.com/67107744/236688027-b05d3942-a970-4957-b6f2-0c462e7391dd.PNG)
